### ISSUE TITLE
Issue with NocSkillsAPI

### ISSUE THREAD

**Issue by ZebGirouard** [HubSpot/noc-skills#3]
1) Seems like NocSkillsAPI fails to start, other programs seem OK.  [See code chunk A]

2) This also means NocSkillsAPI is not listening on port 24080.  [See code chunk B]

3) Probable cause of this problem: directory or file not found.  I tried adding this file, but since it seems to be a temp directory, the file deletes itself after a short time.  Not sure how to resolve.  [See code chunk C]

A)

[root@ip-10-62-5-152 init.d]# ./mongod status
mongod (pid 814) is running...

[root@ip-10-62-5-152 init.d]# ./NocSkillsWeb start  
Starting gunicorn
Spawning NocSkillsWeb

[root@ip-10-62-5-152 init.d]# ./NocSkillsAPI status  
NocSkillsAPI is stopped

B)

[root@ip-10-62-5-152 init.d]# netstat -tulpn  
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address               Foreign Address             State       PID/Program name  
tcp        0      0 0.0.0.0:28017               0.0.0.0:\*                   LISTEN      814/mongod  
tcp        0      0 0.0.0.0:22                  0.0.0.0:\*                   LISTEN      715/sshd  
tcp        0      0 127.0.0.1:25                0.0.0.0:\*                   LISTEN      799/master  
tcp        0      0 0.0.0.0:8000                0.0.0.0:\*                   LISTEN      1037/python  
tcp        0      0 0.0.0.0:27017               0.0.0.0:\*                   LISTEN      814/mongod  
tcp        0      0 :::22                       :::\*                        LISTEN      715/sshd            

C)

[root@ip-10-62-5-152 init.d]# ./NocSkillsAPI start  
Starting NocSkillsAPI: cat: /var/run/NocSkillsAPI.pid: No such file or directory
                                                           [FAILED]

-Tim Girouard, Applicant for NOC Engineer position

**Comment by marlier** [comment]
Hey, Tim --

Thanks for taking the time to run through this.  Would you be willing to take a little more time working with the NocSkillsAPI issue?  This is a good start, but doesn't identify the problem in this case.

**Comment by ZebGirouard** [comment]
Alright, I'll try to dive in to it tonight.

Thanks Ian,
Tim

**Comment by ZebGirouard** [comment]
Definitely got further, NocSkillsAPI is running, but not sure if my fix was
too arbitrary.
